### ISSUE TITLE
Differentiating between Raw/unprocessed scans and processed/derived scans

### ISSUE THREAD

**Issue by raamana** [Open-Minds-Lab/mrQA#49]
we need a way to differentiate between raw (EPI) scans and processed data (Motion Corrected by Siemens)... another instance of raw vs. derived data is from ASL / perfusion weighted images also

**Comment by sinhaharsh** [comment]
Seems like ImageType Attribute can be used to differentiate between raw and derived data. Raw scans have the value `ORIGINAL`, and the Derived sequences have the value `DERIVED`.

For example,
| Modality | Image Type Attribute | 
|--|--|
|AAHead_Scout_64ch-head-coil_MPR_cor |['DERIVED', 'PRIMARY', 'MPR', 'ND', 'NORM']|
|T2w_FLAIR | ['ORIGINAL', 'PRIMARY', 'M', 'NORM', 'DIS2D'] |
| asl_3d_MedAir | ['ORIGINAL', 'PRIMARY', 'ASL', 'NONE', 'ND', 'NORM', 'MOSAIC'] |
|Perfusion_Weighted | ['DERIVED', 'PRIMARY', 'ASL', 'ND', 'NORM', 'SUB', 'TTEST', 'MOSAIC'] |
|MoCoSeries | ['ORIGINAL', 'PRIMARY', 'M', 'ND', 'NORM', 'MOCO', 'MOSAIC'] |

It is interesting how MocoSeries is not annotated as DERIVED.  But we can use the string 'MOCO' to detect it.

Relevant Discussion: https://github.com/nipy/heudiconv/issues/266

**Comment by raamana** [comment]
fantastic - great find. we can inject a filter for this. 

We need to have a modular and easy way to maintain various list of filters, based on various attributes (dicom tags, file names etc) some to be ignored (directly at the `MRdataset`) and some to be not reported at the report level. Let's `gather requirements` (soft terminology) and make a plan for how to implement it first before delving into it.

also, we need to document it well, which reminds, we need a new page in mrQA docs explaining how users should read our report. for the most part it is very self explanatory, but they need to know the different sections, and what is being ignored while generating the report for the sake of completeness

**Comment by neurolabusc** [comment]
Be warned [Siemens](https://github.com/rordenlab/dcm2niix/issues/236) enhanced DICOMs only use [specification defined](https://dicom.innolitics.com/ciods/rt-dose/general-image/00080008) [values](https://dicom.nema.org/medical/dicom/2017d/output/chtml/part03/sect_C.8.3.html#sect_C.8.3.1.1.1) in the ImageType field (0008,0008). Therefore, I would expect terms like MOCO would appear in the ImageTypeText field (0021,1175). For this reason, data from a Siemens XA scanner will vary the verbosity of 0008,0008 when exporting to classic versus enhanced DICOM.

For examples, see XA30 [classic](https://github.com/neurolabusc/dcm_qa_xa30i) and [enhanced](https://github.com/neurolabusc/dcm_qa_xa30) images.

I think `derived` is in the eye of the beholder for reconstructed MR data.

**Comment by raamana** [comment]
thanks for the warnings and details Chris, appreciate it, although we didn't need even more complexity to worry about :).

is the Enhanced DICOM the only format available from the XA30 versions going forward? what libraries do you recommend for reading Enhanced DICOMs? I hope the `pydicom` or `dcmstack` or one of your libraries does the job for us, so we can focus on mrQA :)

**Comment by sinhaharsh** [comment]
We are using ImageType Attribute to detect Moco series and derived sequences in [dicom_utils](https://github.com/sinhaharsh/MRdataset/blob/c09cad2dc1f72c82bc42051ba331b6407799700b/MRdataset/dicom_utils.py#L41)
