### ISSUE TITLE
Testing

### ISSUE THREAD

**Issue by sinhaharsh** [Open-Minds-Lab/mrQA#6]
Create dummy datasets which can be post publicly, and re-run tests

**Comment by raamana** [comment]
yes, we need to share them, making sure there is no PHI

**Comment by sinhaharsh** [comment]
Guidelines for removing PHI
https://wiki.cancerimagingarchive.net/display/Public/Submission+and+De-identification+Overview

**Comment by raamana** [comment]
Make sure you don't end up doing a ton of manual curation to achieve deidentification.. ideally you only ever have to do it once, when going from a real dataset with PHI to your first simulated dataset without PHI.. and then on, start with the simulated one with no PHI at all.

if you are starting from an already fully open dataset, that's been clearly deidentified by the respective admins (like ADNI etc), then you need not worry, although if you come across PHI, let me know and we can discuss what to do
